# Generated by Django 4.2.23 on 2025-08-04 12:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Video Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Duration in seconds",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(86400),
                        ],
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="Mock URL for video file"),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, help_text="Mock URL for video thumbnail"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("unlisted", "Unlisted"),
                            ("private", "Private"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("channel_name", models.CharField(db_index=True, max_length=100)),
                ("channel_avatar_url", models.URLField(blank=True)),
                ("view_count", models.PositiveIntegerField(db_index=True, default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("dislike_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="videos.videocategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"],
                        name="videos_vide_status_ffba77_idx",
                    ),
                    models.Index(
                        fields=["category", "status"],
                        name="videos_vide_categor_d2ff0e_idx",
                    ),
                    models.Index(
                        fields=["channel_name", "status"],
                        name="videos_vide_channel_93636c_idx",
                    ),
                    models.Index(
                        fields=["-view_count"], name="videos_vide_view_co_02bc14_idx"
                    ),
                    models.Index(
                        fields=["-like_count"], name="videos_vide_like_co_f8ad1d_idx"
                    ),
                ],
            },
        ),
    ]
