# Generated by Django 4.2.23 on 2025-08-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=1000)),
                ('author_name', models.CharField(max_length=100)),
                ('author_avatar_url', models.URLField(blank=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video', 'is_approved'], name='comments_co_video_i_7f3ca4_idx'), models.Index(fields=['is_ai_generated'], name='comments_co_is_ai_g_aca252_idx')],
            },
        ),
    ]
